### ISSUE TITLE
Fix outdated Readme 

### ISSUE THREAD

**Issue by teameh** [bitrise-steplib/steps-xcode-test#105]
This readme seems generic and does not tell me anything on how to use this step. 

Yes, I can check `step.yml` and try to find the the documentation I'm looking for, but it would be way more user-friendly if it would be listed in the readme 😃. Maybe the readme could be auto-generated from the `step.yml`?

**Comment by teameh** [comment]
Something like this: https://github.com/teameh/steps-xcode-test/blob/master/generate-readme.js
    
```
$ node ./generate-readme.js
```

Result: https://github.com/teameh/steps-xcode-test/blob/master/README.md 

I just used node since I don't know any Go, but you could probably rework something like this (also with a bit better formatting) in Go?

**Comment by tamasbazs** [comment]
Hi @teameh ,
Sorry for the late reply here! Just wanted to let you know that we have a task for this created for out tooling team and they already gathered all the needed infos for implementing it and making the README generation automated. 😉I added this thread to the notification of the list so you will receive a notification as soon as the tooling team implements this feature!

**Comment by teameh** [comment]
Awesome! Looking forward to it! Thanks!

**Comment by teameh** [comment]
Still important to me

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. You can find an example of an [updated README file](https://github.com/bitrise-steplib/steps-go-list/pull/8) on this related PR. Until then, feel free to create a feature request and share your thoughts and ideas on Discuss.

Happy building! 🚀
