### ISSUE TITLE
Can you expose the xccovreport file ?

### ISSUE THREAD

**Issue by mackoj** [bitrise-steplib/steps-xcode-test#113]
I want to be able to process the `.xccovreport` with xccov in order to retrieve the code coverage info.

**Comment by fehersanyi-bitrise** [comment]
Hy @mackoj I will create a task for the tooling team with this, they will get back to you when they done it.

**Comment by mackoj** [comment]
Thanks @fehersanyi-bitrise today you allow us to create this file but the file path is not available in the output variable of the step.

**Comment by fehersanyi-bitrise** [comment]
Yes I know what you mean, the file is there, but it would be easier to manage is the step exposed like a $XCCOV_REPORT_PATH variable or something with the path to the file 🙃

**Comment by mackoj** [comment]
Exactly ! 😁

**Comment by icPJmobile** [comment]
Is there any progression on this issue ? thanks

**Comment by fehersanyi-bitrise** [comment]
Hello @icPJmobile 
unfortunately the tooling team could not yet take up the task.

**Comment by mackoj** [comment]
Have you made some progress on this point @fehersanyi-bitrise ?

**Comment by bitce** [comment]
Hi @mackoj!

This wasn't completed just yet, as promised we will definitely declare this on this thread once it is! Thanks for the patience 🙂

**Comment by abotkin-cpi** [comment]
So we got a version of this working in our Bitrise builds for Xcode 11+ specifically.  Due to the new format of xcresult starting from Xcode 11, our intern made a tool called [xcparse](https://github.com/ChargePoint/xcparse) for extracting out the code coverage file from a given xcresult path (Bitrise's handy `$BITRISE_XCRESULT_PATH`).  We then have a step where we install the Swift command line tool via Homebrew (important to disable the upgrade part since it doesn't play well with the tap install).  At that point, we have the action.xccovreport in the source directory & use it with xcov.

From our Bitrise.yml

```
    - brew-install@0.9.0:
        inputs:
        - upgrade: 'no'
        - packages: ChargePoint/xcparse/xcparse
        title: Brew install xcparse
        is_always_run: true
    - script@1.1.5:
        inputs:
        - content: |-
            #!/usr/bin/env bash

            # Extract Xcode 11 xcovreport
            echo $BITRISE_XCRESULT_PATH

            xcparse -x "$BITRISE_XCRESULT_PATH" .

            cp action.xccovreport $BITRISE_DEPLOY_DIR

            zip -r xcresult.zip $BITRISE_XCRESULT_PATH
            cp xcresult.zip $BITRISE_DEPLOY_DIR
        title: Extract xccovreport
        is_always_run: true
    - script@1.1.5:
        title: xcov
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # debug log
            set -x

            bundle install
            bundle exec xcov -w $BITRISE_PROJECT_PATH -s $BITRISE_SCHEME -f action.xccovreport -o reports
            zip -r $BITRISE_DEPLOY_DIR/xcov_report.zip reports/*
        is_always_run: true
```

**Comment by bitce** [comment]
This is really great @abotkin-cpi, thanks for sharing!

**Comment by brandtdaniels** [comment]
It looks like xcov is broken with Xcode 11, so I wonder how this worked.
https://github.com/fastlane/fastlane/issues/15295

**Comment by abotkin-cpi** [comment]
@brandtdaniels In the steps I had above, you need to have the two steps before the xcov step - one that installs the ChargePoint xcparse tool via Homebrew & the second step to use xcparse to get the xccovreport out of the xcresult file.  The log you gave seems to imply you don't have those two steps.

That said, since I wrote that answer, Fastlane took ownership of xcov and their maintainer updated xcov so that the -f option can now take the xcresult directly (rather than having to use xcparse to get it for you).  So you could change towards something like this:

`bundle exec xcov -w $BITRISE_PROJECT_PATH -s $BITRISE_SCHEME -f $BITRISE_XCRESULT_PATH -o reports`

**Comment by brandtdaniels** [comment]
`Brew install xcparse` and `Extract xccovreport` were both successful. I'll try your edit above.

**Comment by brandtdaniels** [comment]
I tried using the command directly on my local machine before setting up bitrise to do it and I got this error, which is the same error I got before:

```
Opening .xccoverage file at path: /var/folders/ry/zb2fv35j261fgt86bjndkl5m0000gp/T/d20191025-68799-1rwr3nw/action_0.xccovreport
Parsing .xccoverage file...
File successfully parsed
[13:04:08]: Exit status:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: xcov (/Users/bdaniels/.rbenv/versions/2.6.3/bin/xcov)
RuntimeError: [!] Error creating your coverage report - see the log above
  /Users/bdaniels/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcov-1.6.0/lib/xcov/error_handler.rb:20:in `handle_error'
```

**Comment by brandtdaniels** [comment]
> rather than having to use xcparse to get it for you
Are you saying xcparse is not necessary anymore?

**Comment by brandtdaniels** [comment]
The issue could be because I'm using Catalina locally, however on Bitrise they don't offer Catalina yet and I'm still seeing an issue.

https://github.com/fastlane-community/xcov/issues/159

**Comment by abotkin-cpi** [comment]
> I tried using the command directly on my local machine before setting up bitrise to do it:
> 
> `bundle exec xcov -w CRM.xcworkspace -s CRM -f /Users/bdaniels/Library/Developer/Xcode/DerivedData/CRM-eadpxzelozpjpsbwotctvgpnhvoi/Logs/Test/Test-CRM-2019.10.25_10-42-06--0700.xcresult -o reports`
> 
> and I got this error, which is the same error I got before:
> 
> ```
> Opening .xccoverage file at path: /var/folders/ry/zb2fv35j261fgt86bjndkl5m0000gp/T/d20191025-68799-1rwr3nw/action_0.xccovreport
> Parsing .xccoverage file...
> File successfully parsed
> [13:04:08]: Exit status:
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> Found no similar issues. To create a new issue, please visit:
> https://github.com/fastlane/fastlane/issues/new
> Run `fastlane env` to append the fastlane environment to your issue
> bundler: failed to load command: xcov (/Users/bdaniels/.rbenv/versions/2.6.3/bin/xcov)
> RuntimeError: [!] Error creating your coverage report - see the log above
>   /Users/bdaniels/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcov-1.6.0/lib/xcov/error_handler.rb:20:in `handle_error'
> ...
> ```

Yeah with xcov 1.6, you don't even need xcparse if you pass the xcresult directly.  xcparse was being used as a crutch when xcov could only take the xccovreport directly.  The error you got here seems like an issue with xcov separate from not finding the file now (and you are using xcov 1.6 so not an issue of an old version).  If you could get the full stacktrace of the RuntimeError, I'd open a new ticket over in the xcov project with that.

**Comment by brandtdaniels** [comment]
Looks like xcov 1.7 was released and fixed the issue!

**Comment by jaswanth-transpire** [comment]
> @brandtdaniels In the steps I had above, you need to have the two steps before the xcov step - one that installs the ChargePoint xcparse tool via Homebrew & the second step to use xcparse to get the xccovreport out of the xcresult file. The log you gave seems to imply you don't have those two steps. If you do have those steps, see if you can attach the logs from those steps too.
> 
> That said, since I wrote that answer, Fastlane took ownership of xcov and their maintainer updated xcov so that the -f option can now take the xcresult directly (rather than having to use xcparse to get it for you). So you could change towards something like this:
> 
> `bundle exec xcov -w $BITRISE_PROJECT_PATH -s $BITRISE_SCHEME -f $BITRISE_XCRESULT_PATH -o reports`

After so many different methods, `bundle exec xcov -w $BITRISE_PROJECT_PATH -s $BITRISE_SCHEME -f $BITRISE_XCRESULT_PATH -o reports` is what worked for me. Thanks!
