### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by gmann1** [bitrise-steplib/steps-xcode-test#114]
❌  Undefined symbols for architecture x86_64
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: 

https://app.bitrise.io/build/2dff269be9aed34b

Tests run fine locally- any advice?

**Comment by fehersanyi-bitrise** [comment]
Hy there, as I see you are building on xcode 10.2, I checked the dependency that throws an error, you are using 4.1.2 of RxSwift, and based on their repository https://github.com/ReactiveX/RxSwift/releases
xcode 10.2 compatibility is RxSwift 4.5 and higher, could you try updating the dependency?

**Comment by gmann1** [comment]
Thanks for your help!
