### ISSUE TITLE
Adding parameters to xcpretty don't work has expected

### ISSUE THREAD

**Issue by mackoj** [bitrise-steplib/steps-xcode-test#119]
As you can see here https://app.bitrise.io/build/0e9d17a6044f17b7#?tab=log I try to add
```txt
-f `xcpretty-json-formatter`
```
to **xcpretty** instead it create
```txt
"-f" "`xcpretty-json-formatter`"
```
and it hang the vm. 

I want to be able to remove the double-quote that are added for each parameter of **xcpretty**. How can I do it ? Should I fork this project and use the fork only or can you fix it ?

Thanks,

**Comment by mackoj** [comment]
I did find a way to fix it but the auto double quoting is still very annoying...

**Comment by AvdLee** [comment]
@mackoj how did you fix this? I'm running into the same issue and would like to fix it!

**Comment by mackoj** [comment]
Hi @AvdLee I didn't really remember how I fix it but at the end I did do the command myself in script step.

**Comment by AvdLee** [comment]
@mackoj that's too bad! To make use of the Fastlane and Danger features we sometimes need a different xcpretty formatter. It would be great to have this fixed. I'll re-open this in a new issue!
