### ISSUE TITLE
Underlying error: Failed to install the requested application. The application's Info.plist does not contain CFBundleVersion.

### ISSUE THREAD

**Issue by ThomasLeblond** [bitrise-steplib/steps-xcode-test#122]
Hello guys,

I'm facing to an issue on Bitrise for xcode-test step with Xcode 11 GM 2.

```
Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={bundleURL=file:///Users/vagrant/Library/Developer/Xcode/DerivedData/FinalCAD-Swift-dxawxuidwwedvqdgesklqkhnncjw/Build/Products/Debug-iphonesimulator/FINALCAD.app/, NSLocalizedFailureReason=The application's Info.plist does not contain CFBundleVersion., NSLocalizedRecoverySuggestion=Ensure your bundle contains a CFBundleVersion., NSLocalizedDescription=Failed to install the requested application}
```

I can't reproduce on my Mac but only on Bitrise and it seems to be related to the new `CoreSimulator.framework`.

```
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_release_notes

"Bundles without a CFBundleVersion are invalid and can't be properly installed on devices or simulators. CoreSimulator now checks and rejects such bundles earlier in the process with a clearer error message. (49892531)"
```

My `CFBundleVersion` is correctly configured in my `Info.plist` but the tests always failed on Bitrise with this error message.

It seems to be related to a cache in `CoreSimulatorBridge` (https://stackoverflow.com/questions/56450295/cannot-run-application-on-simulator-after-installing-xcode-11-cfbundleversion).

I have another workflow for another application with the same steps and I don't have this issue for Xcode 11.

Thanks!

**Comment by wSwinsonEntercom** [comment]
Same thing. It's been broken since you posted that and still is. Could never figure out what it was and unit tests in CLI have been broken since.

**Comment by non-binary** [comment]
Hi @ThomasLeblond, @wSwinsonEntercom,

Thank you for reaching out.

Can you try deleting the contents of the DerivedData directory at some point earlier in the build (before you experience this error) using a script step:

```
rm -rf ~/Library/Developer/Xcode/DerivedData
```

Bitrise does not cache the DerivedData directory between builds (by default) however I've seen similar issues in the past and deleting the derived data can help us get in the right direction debugging wise.

Can you also share your bitrise.yml file as well as a full log for the build you're experiencing this in? If you wish to provide that information privately, please email letsconnect [at] bitrise.io and mention/link to this GH issue.

Thanks and looking forward to hearing from you.

Kind regards,
Luna

**Comment by non-binary** [comment]
Oh and one last thing, can both of you confirm whether or not your projects have **ever** successfully built on Bitrise or if you are new to the platform? Thanks

**Comment by wSwinsonEntercom** [comment]
@non-binary @ThomasLeblond  It was, embarrassingly, a "Set Info.plist" step that got somehow inserted into our workflow that was messing it up. As soon as i removed that, it was fine. /facepalm

**Comment by non-binary** [comment]
@wSwinsonEntercom No problem! Happens to the best of us. Glad to hear you were able to fix your build!

@ThomasLeblond If you could please check if this is also the source of your issue. If not please provide the information I requested above and we can continue debugging.

Cheers! :)

**Comment by non-binary** [comment]
@ThomasLeblond Do you still need assistance with this?
