### ISSUE TITLE
failed to get simulator udid

### ISSUE THREAD

**Issue by AffirmMobileClient** [bitrise-steplib/steps-xcode-test#128]
Running the Xcode-test step version 2.4.2 starting failing with no changes to our `bitrise.yml`. I'm trying to run an XCUITest target. Below is the output

```
Failed to download step.zip: Failed to download target from: https://bitrise-steplib-collection.s3.amazonaws.com/step-archives/xcode-test/2.4.2/step.zip
+------------------------------------------------------------------------------+

| (1) xcode-test                                                               |
+------------------------------------------------------------------------------+
| id: xcode-test                                                               |
| version: 2.4.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-11-08T16:00:49Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[16:00:49]  * [OK] Step dependency (xcode) installed, available. 
INFO[16:00:49]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectPath: affirm/Affirm.xcodeproj
- Scheme: XCUITests-Sandbox
- SimulatorPlatform: iOS Simulator
- SimulatorDevice: iPhone 11 Pro
- SimulatorOsVersion: 13.1
- OutputTool: xcodebuild
- IsCleanBuild: false
- IsSingleBuild: true
- ShouldBuildBeforeTest: true
- ShouldRetryTestOnFail: false
- GenerateCodeCoverageFiles: false
- ExportUITestArtifacts: true
- DisableIndexWhileBuilding: true
- TestOptions: -parallel-testing-enabled NO -maximum-parallel-testing-workers 1
- XcprettyTestOptions: --color --report html --output "/Users/vagrant/deploy/xcode-test-results-.html"
- Verbose: false
- HeadlessMode: false
- CacheLevel: swift_packages
* action: -project
- xcodebuildVersion: Xcode 11.1 (Build version 11A1027)
Export UITest Artifacts (export_uitest_artifacts) turned on, but Xcode version >= 11. The test result bundle structure changed in Xcode 11 it does not contain TestSummaries.plist and Attachments directly, nothing to export.
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
failed to get simulator udid, error: %!(EXTRA *errors.errorString=no simulators found for os version: 13.1)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-test (exit code: 1)                                     | 17.46 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-test/issues    |
| Source: https://github.com/bitrise-steplib/steps-xcode-test                  |
+---+---------------------------------------------------------------+----------+
```

If I change the simulator **OS version** from **13.1** to **latest** in the **Xcode Test for iOS** step, then the tests run successfully, using versoin 13.1 anyway

**Comment by tamasbazs** [comment]
Hi there,

Thank you so much for bringing this issue to our attention! We are really sorry for the inconvenience caused, the latest 2.4.2 version of the Xcode Test for iOS step has an issue where defining an OS Version to use instead of using the latest results in an error during the step run. Our Tooling team is currently working on resolving this issue. 
In the meantime you can either downgrade the step to the 2.4.1 version where you can specify the OS version or you can set the OS version to latest.

**Comment by adamwaite** [comment]
Hi @tamasbazs. We are using version 2.4.6 of Xcode Test and `latest` and we're seeing this error too.

**Comment by bitce** [comment]
Hi @adamwaite! If you're seeing this error, chances are you are trying a combination of device and OS that's not installed by default on the environment you're using.

You can check the pre-installed ones here: https://github.com/bitrise-io/bitrise.io/tree/master/system_reports

**Comment by PVoola** [comment]
Though It is supported by list of devices iPad Air 2 from the above mentioned system reports : still I'm facing the following issue: 

INFO[09:16:37]  * [OK] Step dependency (xcode) installed, available. 
INFO[09:16:37]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectPath: Sumeru.xcworkspace
- Scheme: SumeruStudyCrawler
- SimulatorPlatform: iOS Simulator
- SimulatorDevice: iPad Air 2
- SimulatorOsVersion: latest
- OutputTool: xcpretty
- IsCleanBuild: false
- IsSingleBuild: true
- ShouldBuildBeforeTest: true
- ShouldRetryTestOnFail: false
- GenerateCodeCoverageFiles: false
- ExportUITestArtifacts: false
- DisableIndexWhileBuilding: true
- Verbose: true
- HeadlessMode: true
- CacheLevel: swift_packages

failed to get simulator udid, error: failed to determin latest (iOS) simulator version
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-test (exit code: 1)                                     | 16.83 sec|

**Comment by Karthikdp92** [comment]
Even after downgrading the version of Xcode Test to 2.4.1 and latest for the OS version, I am still facing this issue

`INFO[12:02:49]  * [OK] Step dependency (xcode) installed, available. 
INFO[12:02:49]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectPath: XXX.xcworkspace
- Scheme: XXX
- SimulatorPlatform: iOS Simulator
- SimulatorDevice: iPhone Xs Max
- SimulatorOsVersion: latest
- OutputTool: xcpretty
- IsCleanBuild: false
- IsSingleBuild: true
- ShouldBuildBeforeTest: true
- ShouldRetryTestOnFail: false
- GenerateCodeCoverageFiles: false
- ExportUITestArtifacts: false
- DisableIndexWhileBuilding: true
- TestOptions: 
- XcprettyTestOptions: --color --report html --output "/Users/vagrant/deploy/xcode-test-results-XXX.html"
- Verbose: false
- HeadlessMode: true
- CacheLevel: swift_packages
* action: -workspace
- xcodebuildVersion: Xcode 11.6 (Build version 11E708)
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
failed to get simulator udid, error: %!(EXTRA *errors.errorString=failed to get latest os version, error: failed to find latest os version for (iOS) - (iPhone Xs Max))`

**Comment by bitce** [comment]
@PVoola that sounds like it might be a different issue, please send us a build URL if it's persistent!
@Karthikdp92  on what stack are you running on when experiencing this? Please send us a build URL too :)
