### ISSUE TITLE
Exporting UITest Artifacts from Xcode 11

### ISSUE THREAD

**Issue by abotkin-cpi** [bitrise-steplib/steps-xcode-test#129]
Hey Bitrise,

Was wondering what your plans are for exporting Xcode 11 attachments & screenshots in the Xcode Test step as I saw it noted that this step hasn't been updated for that yet.  My company has an open source Swift CLI tool we're installing via Homebrew that does the Xcode 11 extraction & we got a request to make a Bitrise step for the functionality (https://github.com/ChargePoint/xcparse/issues/29).  So that's left me with these questions:

1. Do you have any short term plans of implementing your own extraction for Xcode 11 xcresult?
2. If not, would you be open to adding a dependency to our Homebrew tap formula in this step to get such an ability?
3. Or should this Xcode 11 xcresult attachment extraction business be its own Bitrise step separate from Xcode Test as suggested by the enhancement request we got?

**Comment by abotkin-cpi** [comment]
We've got a working prototype over at https://github.com/ChargePoint/bitrise-step-xcparse for anyone who needs to extract screenshots or logs/diagnostics from their Xcode 11 xcresult.  There's a lot that needs to be added for customization, but may be enough for folks who have no access to their screenshots/logs in their Bitrise workflows right now.  Feel free to open tickets in that project for feature requests.

**Comment by abotkin-cpi** [comment]
We've submitted a PR to the Bitrise Steplib to add the xcparse step from the Bitrise Workflow Editor (bitrise-io/bitrise-steplib#2306).

**Comment by Roland-Bak** [comment]
Hi there @abotkin-cpi! Thanks for the pull request, the Tooling Team has already been notified, and will get on reviewing it as soon as they can 🙂

**Comment by abotkin-cpi** [comment]
@Roland-Bak Feel free to close this ticket if you'd like.  As the xcparse step is now available to be added via Bitrise.io's Workflow Editor now (interested folks can check this [README](https://github.com/ChargePoint/bitrise-step-xcparse) for instructions), there's a suitable workaround for Xcode 11.
