### ISSUE TITLE
Allow backticks to work with XCPretty

### ISSUE THREAD

**Issue by AvdLee** [bitrise-steplib/steps-xcode-test#134]
Best explanation can be found in this, already closed issue: https://github.com/bitrise-steplib/steps-xcode-test/issues/119#issuecomment-563249461

To get the most out of both Fastlane and Bitrise, a requirement is needed to pass in a custom formatter for XCPretty. This, however, requires us to use backticks: `

See the linked issue for more details.

**Comment by jschmid** [comment]
Any update on this issue?

**Comment by bitce** [comment]
HI @jschmid and @AvdLee 

There is no update for us to provide, unfortunately. We'll make sure to do so once there is!

**Comment by brki** [comment]
As a workaround on bitrise:

Add a script step before the Xcode Tests step:
```
#!/usr/bin/env bash
# fail if any commands fails
# set -e
set -x

# Ensure that xcpretty-json-formatter is installed; this is used in the "Xcode Test for iOS" step.
bundle install

# Set the XCPRETTY_JSON_FORMATTER environment variable for later steps.
# It is used in the "Xcode Test for iOS" step.
envman add --key XCPRETTY_JSON_FORMATTER --value "$(bundle exec xcpretty-json-formatter 2>/dev/null)"
```

And then in the Xcode Tests step, use this for the `Additional options for xcpretty test call` value:
```
-f $XCPRETTY_JSON_FORMATTER
```
