### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by j-won-o** [bitrise-steplib/steps-xcode-test#142]
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
❌  Undefined symbols for architecture x86_64
xcode test failed, error: exit status 65

Tests run okay in local machine, but not work in bitrise

**Comment by non-binary** [comment]
Hi @j-won-o,

Please open a ticket on https://www.bitrise.io/bitrise-support. We will help you resolve this over email. Thank you.
