### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by jeffveleze** [bitrise-steplib/steps-xcode-test#145]
Hello!

Suddently this error started happening to us, i've checked [this](https://github.com/bitrise-steplib/steps-xcode-test/issues/136) but we do have the release configuration setup, tests are running perfect locally, do you know what could be happening? 

Thanks!

https://app.bitrise.io/build/ab474325e7c10733#?tab=log

**Comment by non-binary** [comment]
Hi @jeffveleze,

Thank you for reaching out. Can you please enable support access so I can access your build?
