### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by johnkodes** [bitrise-steplib/steps-xcode-test#146]
Hello!

```
▸ Linking PhilzKitTestHost
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
▸ Linking PhilzKitTestHost
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

We have this error within our builds. I checked the other threads but we have configurations set. Tests and Bitrise CLI locally works. 

https://app.bitrise.io/build/0f5fdfc12ed3cb62#?tab=log - support enabled

Thank you very much!

**Comment by non-binary** [comment]
Hi @johnkodes,

Please open a ticket here: https://www.bitrise.io/bitrise-support.
