### ISSUE TITLE
Make "-project" optional for swift packages

### ISSUE THREAD

**Issue by noremac** [bitrise-steplib/steps-xcode-test#148]
I would like to use this step to build and run tests on a swift package, but it's not currently possible because this step requires that you define a path to a project or a workspace. After some digging, I've discovered that `-project` is actually not necessary for running tests with xcodebuild against swift packages. The following invocation works fine:

``` sh
xcodebuild test -scheme <my-scheme> -destination 'platform=iOS Simulator,name=iPhone 12'
```

I _could_ generate an Xcode project manually, but I've found that the resulting project made using `swift package generate-xcodeproj` can often have odd build errors not present when simply using `xcodebuild test`.

Could `-project` be made optional so that this step would be more compatible with SPM?

**Comment by non-binary** [comment]
I've made a note internally but we welcome pull requests if you wish to have this sooner. Thank you!
