### ISSUE TITLE
Missing devices in osx-xcode-12.1.x.log 

### ISSUE THREAD

**Issue by xavigil** [bitrise-steplib/steps-xcode-test#153]
### Issue description

We are seeing `failed to get simulator udid, error: failed to determin latest (iOS) simulator version` in our builds when trying to run with Xcode 12.1

The list of devices is empty in https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-12.1.x.log

It looks like by mistake you have removed the list of devices from that environment last Friday https://github.com/bitrise-io/bitrise.io/commit/d2befec775b9a5ce961f561ffda68e65648fce18#diff-2aad232312797651f41288d96f989db1c02cd6d514409d71c21f8847b595fb9eR971

### Bitrise info

- Build URL: https://app.bitrise.io/build/00bcba8946f8c98e#?tab=log

Please let us know if that is the cause of our issue.

Best regards

**Comment by csk4ta** [comment]
Hi @xavigil!

Thanks so much for bringing this to our attention.

Our engineers are currently investigating this issue! I'll post it here as soon as I have any updates!

Thanks for your patience!

**Comment by csk4ta** [comment]
Hi @xavigil!

Just wanted to let you know that the issue has been resolved. 🎉  Could you please check on your end as well? 
Thank you!

**Comment by xavigil** [comment]
On our side is working again 🙌 

Thanks for the quick response @csk4ta

**Comment by akaralar** [comment]
@csk4ta Hello, I'm having this same issue, build URL is https://app.bitrise.io/build/6b3468231aabe039#?tab=log

**Comment by xavigil** [comment]
Unfortunately the list of devices is empty again in your log file https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-12.1.x.log

Can you please have a look?

**Comment by csk4ta** [comment]
Hi everyone, 

Thank you for pinging me about this. I am so sorry that this is happening again! 

I am looking into this with our Infra team. I'll let you know here as soon as I have more information. Thank you so much for your patience!

**Comment by csk4ta** [comment]
We're still looking but in the meantime, it seems a short term fix could be to specify the version to target to get you unblocked, ie. change the step input from `latest` to the version you want to target here:

<img width="1042" alt="Image 2021-03-16 at 2 25 56 PM" src="https://user-images.githubusercontent.com/48446597/111360891-a9960e80-8663-11eb-96d7-00afe5c4ac1b.png">

**Comment by ignkarman** [comment]
Hello @csk4ta ! My organization is currently experiencing this issue, with the Xcode 12.1 Stack, and we are using `latest` for `OS Version`. We are experiencing this across several projects. 

Are there any other suggested workarounds?

**Comment by Roland-Bak** [comment]
Hello there @ignkarman 👋

I wanted to let you know that the developers have rolled out a fix for Xcode 12.4, 12.3 and 12.2 as well, and 12.1 should soon be included as well, but in the meantime you can work around this issue the way @csk4ta mentioned, by specifying the version instead of leaving it on `latest`

Hope this helps! 🙂

**Comment by Buza** [comment]
I am also experiencing this issue. Both manually setting the OS version to something like 14.5 **and** setting it to latest produce the same error. 

Are there any other updates to this issue?

https://app.bitrise.io/build/fd2f8c52642571b3#?tab=log

**Comment by cdhrtp** [comment]
@Buza Are you still having this issue?   If so, can you enable support access and provide the latest build URL that shows this issue?
