### ISSUE TITLE
Error compiling framework

### ISSUE THREAD

**Issue by sueliosousa** [bitrise-steplib/steps-xcode-test#179]
### Issue description

When compiling the Starscream framework, it shows the error that filename Compression file is used twice, but it never shows this error when I run the app in xcode.

<pre>
 error: filename "Compression.swift" used twice: '/Users/vagrant/git/Pods/Starscream/Sources/Starscream/Compression.swift' and /Users/vagrant/git/Pods/Starscream/Sources/Compression/Compression.swift
  </pre>

**Comment by Roland-Bak** [comment]
Hello there @sueliosousa 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by sueliosousa** [comment]
[apps_ff6d294b7343a8b1_fb337e7d-da9d-48c3-aea2-474dbe797f52-full.txt](https://github.com/bitrise-steplib/steps-xcode-test/files/6969354/apps_ff6d294b7343a8b1_fb337e7d-da9d-48c3-aea2-474dbe797f52-full.txt)

**Comment by sueliosousa** [comment]
Hello, is the file being analyzed?

**Comment by Roland-Bak** [comment]
Hello @sueliosousa 👋

Thank you for your patience, but we require additional information in order to advance, could you please send us the URL of the related build as well? Please make sure to enable Support Access as well! 🙂

**Comment by sueliosousa** [comment]
Hello, 

I enabled Support Access.

This is the URL: 
https://app.bitrise.io/build/fb337e7d-da9d-48c3-aea2-474dbe797f52#?tab=log

**Comment by Roland-Bak** [comment]
Hello @sueliosousa 👋

Thank you for the access, can you check that Compression.swift is not included twice in the target's "Build Phases" "Compile Sources" settings?
For more information about this subject, please see this thread: https://stackoverflow.com/questions/34838184/xcode-swift-filename-used-twice-build-error

**Comment by sueliosousa** [comment]
Hello, 

I checked that Compression.swift, it is not included twice.

**Comment by bitce** [comment]
Hey @sueliosousa, thanks for confirming. In order to continue investigating this error, we need to see that you can't recreate the error locally. This can be done by running the CLI in with a clean git clone and providing us the logs of the output. Can you please do the steps described below? 

 https://blog.bitrise.io/post/how-to-debug-your-build-locally
