### ISSUE TITLE
Sometimes fails with an error: Failed to establish communication with the test runner

### ISSUE THREAD

**Issue by redryerye** [bitrise-steplib/steps-xcode-test#190]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? SPORADIC
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I’ve been using the step on my project for a while, and running the step on Bitrise.io sometimes fails.
When I clear cache from Settings, it sometimes succeeds.

Version:
- Destination: platform=iOS Simulator,name=iPhone 8 Plus,OS=latest
- xcodebuildVersion: Xcode 13.0 (Build version 13A233)

The issue has been existing for a while, prior to xcode-test v4.0.0 / XCode 13.0.

### Bitrise info

- Build URL: _https://app.bitrise.io/build/679c72e8-7ffc-4340-bbb8-753289794b2d#?tab=log_
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
Testing failed:
	FooTests:
		Foo encountered an error (Failed to prepare device 'Clone 3 of iPhone 8 Plus' for impending launch. If you believe this error represents a bug, please attach the result bundle at /var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/XCUITestOutput323952820/Test.xcresult. (Underlying Error: Unable to boot the Simulator. launchd failed to respond. (Underlying Error: Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding)))
  </pre>
</details>

**Comment by Roland-Bak** [comment]
Hello @redryerye 👋

Can you let me know if the issue still happens with the latest, 4.0.1 version of Xcode Test?

If it does could you try pre-starting the simulator in advance? You can do so by adding a Script Step before the tests run, such as this example:

npm install -g ios-sim
ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-8, 14.4"
sleep 60
