### ISSUE TITLE
Can't run SPM Targets without a project

### ISSUE THREAD

**Issue by fepersembe** [bitrise-steplib/steps-xcode-test#197]
### Troubleshooting

- [ x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? Current
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME

### Useful information

I am trying to run tests without generating xcode files.Package.swift handles too much stuff.

### Issue description

Xcodebuild can run SPM Package Tests without need of .xcodeporj or .xcworkspace files. Just -scheme option is enough. This step should support that too. 

### Steps to reproduce

1.  Add a Xcodebuild step for an SPM repository without an .xcodeporj or .xcworkspace file.
2. Run the workflow.

**Comment by Roland-Bak** [comment]
Hello there @fepersembe 👋 

I wanted to let you know that your request has been recorded and forwarded to the Product Team for consideration 🙂

**Comment by fepersembe** [comment]
Thank you @Roland-Bak 🙂

**Comment by jcabreram** [comment]
I agree this would be great! If at least the project path could be left empty (so that there is no `-project` or `-workspace` parameter in the `xcodebuild` command), it would allow testing of Swift Packages without an Xcode project.

**Comment by ofalvai** [comment]
@jcabreram this is fixed by #204, thank you for your patience. Make sure to check out [version 4.1.0](https://github.com/bitrise-steplib/steps-xcode-test/releases/4.1.0) of the step.
