### ISSUE TITLE
Use trainer to make test results more reliable

### ISSUE THREAD

**Issue by iainsmith** [bitrise-steplib/steps-xcode-test#203]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time?  EVERY TIME (when using test retries)
- Is the issue reproducible locally by following our YES (If you write a Unit/UITest that only passes the second time)

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

XCPretty is an unreliably way of passing xcodebuild test results (specifically for parallel testing & retries). Ideally bitrise could adopt https://github.com/tuist/xcbeautify and or https://github.com/fastlane-community/trainer/ to extract test results from the test bundle.

### Bitrise info

- Build URL:  https://addons-testing.bitrise.io/builds/e31d81e0-9590-4632-8fff-aa57d200192c/summary?status=failed
- [Bitrise Support]() enabled: _YES / NO_
- Log: 

<details>
  <pre>
SomethingTests
    ✗ testEndToEndSomething
    ✓ testEndToEndSomething (30.137 seconds)
  </pre>
</details>

### Steps to reproduce

1. XCPretty does not accurately parse xcode 13 test repetitions.
2. See linked build for an example.

**Comment by shams-ahmed** [comment]
Thanks @iainsmith we will be looking into a better solution in the near future.. Will update the ticket once I have more details

**Comment by iainsmith** [comment]
Thanks @shams-ahmed, much appreciated.

**Comment by DamienBitrise** [comment]
Bump
