### ISSUE TITLE
Github Status reported Failure even though tests passed

### ISSUE THREAD

**Issue by nsoojin** [bitrise-steplib/steps-xcode-test#211]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.3
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I have some flaky tests that sometimes fail. So I'm using "Retry on Failure" option for my test plan. However, Bitrise is reporting tests failed even though flaky tests passed on subsequent tries. 

[XCResult](https://storage.googleapis.com/bitrise-build-storage-prod/apps/bbd5fe527c72425d/builds/1d48a2ba-5a42-486f-b81b-077639086396/artifacts/39f7ba2fa8381ad6/Test-Maker.Internal.xcresult.zip?GoogleAccessId=bitrise-website-prod-access%40bitrise-website-prod.iam.gserviceaccount.com&Expires=1658563265&Signature=tdbSh1j7eB6gwTFqm9txvPn1VSj4DUW9Vw4AARbK02STsv9SS1qc3fftm%2BFentzXS4%2BC5Q8kaWx8%2FSeMJ2hKoHWKXKMXqH8AFiS6%2B595DSt%2BEs5vl9iq4JC4ufxnaFP31llcyNwyaFuWOnidsD7kApKNNbcVtIJsTrQrC5RcBw9YjEVeDVC5kZYYshsWIOKV3Xnq%2B74symzU%2BIDJx1cXBpUDBjlm3yhK%2Fex9yqHnOw7dSlVLnfHtP886bgyk%2FwoF5gUqkP3T%2F9PxA1LsCwrvcnF8nz%2BkSFhNAkNClWCQnV3FyZM3o%2BbYu5lFV9j1h%2FromSIMEVvoejiKkmis9hvaUg%3D%3D) here shows that the overall test suite passed with 614 passed tests, 0 failed tests, and 2 mixed tests which are the flaky tests that passed on the second try. However, Bitrise's Test result marks them "failed", so the status for my PR failed.

<img width="1557" alt="Screen Shot 2022-07-22 at 4 04 12 PM" src="https://user-images.githubusercontent.com/3890050/180518865-40c24caa-2d19-4989-92db-ed7aae6348c6.png">

### Expected Result
If retried tests passed, the overall test should be marked successful and Github Status should pass.

### Bitrise info

- Build URL: https://app.bitrise.io/build/1d48a2ba-5a42-486f-b81b-077639086396?tab=details
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES
- Log: 

<details>
  <pre>
 
  </pre>
</details>

**Comment by DamienBitrise** [comment]
Looks like your GitHub Auth Token is invalid so the GitHub Status step cannot send the status back to GitHub

**Comment by DamienBitrise** [comment]
The test report addon does seem to be reporting failures even tho the step passed. Thanks for the report, we will look into this issue.

**Comment by d4rkd3v1l** [comment]
We're facing the same issue, I guess. (step version 4.6)

When a test fails initially, but then passes on retry, the build is passed in Bitrise (as expected), but Bitrise Checks reports a failed status to GitHub.

**Comment by nsoojin** [comment]
@DamienBitrise Can you share an update?

**Comment by nsoojin** [comment]
@DamienBitrise Can you share us an update?

**Comment by lo1tuma** [comment]
Looks like this is duplicate of #195. It seems like only the test report and the github status check is wrongly reported as failed, the bitrise step itself is passing. This is a huge problem for us, because we rely on the github status check which must pass before we allow pull requests being merged.

Is there any update on this bug?

**Comment by lo1tuma** [comment]
This is still an issue.
