### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by AdamBCo** [bitrise-steplib/steps-xcode-test#220]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.7.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

Anytime I try and run bitrise locally, I get the following error when attempting to run the test step.

<img width="868" alt="Screenshot 2023-02-06 at 3 10 42 PM" src="https://user-images.githubusercontent.com/4572275/217108431-2dabf470-2437-4840-868f-32830d9ee88a.png">

### Steps to reproduce
Run bitrise run WORKFLOW NAME locally.

**Comment by nzsrini** [comment]
Any update on this issue, We are also having the same issue.

**Comment by otusweb** [comment]
I managed to solve this issue by updating the go version that bitrise installed at ~/.bitrise/toolkits/go/inst/go/bin/go

I downloaded the archive from https://go.dev/dl/ and simply unarchived the file where the old version was.
You can run `~/.bitrise/toolkits/go/inst/go/bin/go version` to check the installation was successful.

**Comment by alessandrodn** [comment]
When can we have an official fix?

**Comment by alessandrodn** [comment]
It seems the error `undefined: unsafe.Slice` is related to using go version 1.16.5: `unsafe.Slice` has been introduced in 1.17.
It's weird as this module defines a dependency on go 1.17 (in `go.mod`) but this is not enforced.
Is there a command to force bitrise steps to download its dependency?
