### ISSUE TITLE
Failed on 'Clone 1 of iPhone 8 Plus

### ISSUE THREAD

**Issue by AdamBCo** [bitrise-steplib/steps-xcode-test#221]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.7.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? Not able to run locally due to the issues highlighted [here](https://github.com/bitrise-steplib/steps-xcode-test/issues/220)

### Issue description
Our XCode-Test step fails with the following error
<img width="1337" alt="Screenshot 2023-02-06 at 3 17 20 PM" src="https://user-images.githubusercontent.com/4572275/217109040-13bea0f7-afbf-45c8-b99d-d8000ae13f13.png">

### Bitrise info

- Build URL: [Here](https://app.bitrise.io/build/3ab86940-3407-4baa-8669-0bfe36937e75)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES

<details>
  <pre>
Last lines of the build log:
Test case 'StarlingUITests.testAuthentication()' failed on 'Clone 1 of iPhone 8 Plus - StarlingUITests-Runner (17105)' (29.350 seconds)
Test case 'StarlingUITests.testClassicAccountButNoStarlingAccount()' failed on 'Clone 1 of iPhone 8 Plus - StarlingUITests-Runner (17105)' (32.938 seconds)
Test suite 'StarlingUITestsLaunchTests' started on 'Clone 1 of iPhone 8 Plus - StarlingUITests-Runner (17105)'
Test case 'StarlingUITestsLaunchTests.testLaunch()' failed on 'Clone 1 of iPhone 8 Plus - StarlingUITests-Runner (17105)' (35.301 seconds)
Test case 'StarlingUITestsLaunchTests.testLaunch()' failed on 'Clone 1 of iPhone 8 Plus - StarlingUITests-Runner (17105)' (30.420 seconds)
2023-02-06 19:46:38.520 xcodebuild[11155:40334] [MT] IDETestOperationsObserverDebug: 440.103 elapsed -- Testing started completed.
2023-02-06 19:46:38.524 xcodebuild[11155:40334] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-02-06 19:46:38.524 xcodebuild[11155:40334] [MT] IDETestOperationsObserverDebug: 440.103 sec, +440.103 sec -- end
  </pre>
</details>

**Comment by JamesSedlacek** [comment]
I'm experiencing something similar:
Failed to prepare device 'Clone 4 of iPhone 8 Plus' for impending launch.
