### ISSUE TITLE
This step is 10x slower than using xcodebuild - Performance Issues

### ISSUE THREAD

**Issue by mackoj** [bitrise-steplib/steps-xcode-test#240]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 5.0.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Why using this step is 10x slower the using the xcodebuild command ?

### Bitrise info

- Build URL: [using steps-xcode-test](https://app.bitrise.io/build/2c5b8162-0ddd-4873-8acd-6ad3b294e01e?tab=log)  / [using xcobuild cmd](https://app.bitrise.io/build/c4ed7767-d782-4718-9168-af713b258be3)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES

### Steps to reproduce

I did provide two different integration and as you can see using this step is very very slow compared to using the command directly.

**Comment by ofalvai** [comment]
Hey @mackoj, I had a quick look at the build logs and noticed this in the raw xcodebuild run:

```
-destination 'platform=iOS Simulator,name=null,OS=17.0'
```

Because of the null name, later on, this happens:
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:0000FE00-2E2647488FCD4FC3 }
```

...and because of this, I see multiple compilation and test failures, so I don't think the two builds are doing the same amount of work.

**Comment by mackoj** [comment]
Hi @ofalvai,
