### ISSUE TITLE
Failed to update screenshot names - syntax error

### ISSUE THREAD

**Issue by timefrancesco** [bitrise-steplib/steps-xcode-test#99]
Hey there,

I'm encountering the following error:
`Failed to update screenshot names, error: failed to parse TestSummaries.plist, error: plist: error parsing XML property list: XML syntax error on line 6031: illegal character code U+0008
xcode test exit code: 65
xcode test failed, error: exit status 65`

Is there something wrong in my tests or else?

Thank you

**Comment by bitce** [comment]
Hi @timefrancesco! 

Based on the error it seems like, but we can't be sure, can you please include an URL to the build where you are encountering this issue?

**Comment by ccarranzaD3** [comment]
We are encountering this error as well https://app.bitrise.io/build/4e4331cda11ebd36
